import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Container } from "@/components/container";

const inknutAntiqua = localFont({
  src: [
    {
      path: "./fonts/InknutAntiqua-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/InknutAntiqua-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-inknutAntiqua",
});

export const metadata: Metadata = {
  title: "Cat facts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inknutAntiqua.variable} font-sans text-brown h-full md:text-sm`}
      >
        <Container>{children}</Container>
      </body>
    </html>
  );
}
